// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6k4UPN7m3ahD1tdARFsNQjtLr5cWq7tU',
    appId: '1:970146405739:web:5028e71ea841b2964b002e',
    messagingSenderId: '970146405739',
    projectId: 'materium-de9c9',
    authDomain: 'materium-de9c9.firebaseapp.com',
    storageBucket: 'materium-de9c9.firebasestorage.app',
    measurementId: 'G-7P6JDEHXPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdceYl1-eULSCMZXt5stxpvzmYqOUHOh0',
    appId: '1:970146405739:android:5f697dce9cda89094b002e',
    messagingSenderId: '970146405739',
    projectId: 'materium-de9c9',
    storageBucket: 'materium-de9c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5cf3qJgcmYgvT7J04rXupQ9E0gt64ghA',
    appId: '1:970146405739:ios:cbb68c19437cbf9e4b002e',
    messagingSenderId: '970146405739',
    projectId: 'materium-de9c9',
    storageBucket: 'materium-de9c9.firebasestorage.app',
    iosClientId:
        '970146405739-1j196k3rr0qnemb7924616cl0k2ekb47.apps.googleusercontent.com',
    iosBundleId: 'com.example.materiumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5cf3qJgcmYgvT7J04rXupQ9E0gt64ghA',
    appId: '1:970146405739:ios:cbb68c19437cbf9e4b002e',
    messagingSenderId: '970146405739',
    projectId: 'materium-de9c9',
    storageBucket: 'materium-de9c9.firebasestorage.app',
    iosClientId:
        '970146405739-1j196k3rr0qnemb7924616cl0k2ekb47.apps.googleusercontent.com',
    iosBundleId: 'com.example.materiumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6k4UPN7m3ahD1tdARFsNQjtLr5cWq7tU',
    appId: '1:970146405739:web:b7f0e6a60e08ce644b002e',
    messagingSenderId: '970146405739',
    projectId: 'materium-de9c9',
    authDomain: 'materium-de9c9.firebaseapp.com',
    storageBucket: 'materium-de9c9.firebasestorage.app',
    measurementId: 'G-CGWNTV2B9M',
  );
}
